### ISSUE TITLE
Read login and host infos from netrc or a config file

### ISSUE THREAD

**Issue by mseri** [mseri/xapirpc-rs#2]

**Comment by gaborigloi** [comment]
We could also use the `XE_EXTRA_ARGS` env var that the `xe` CLI uses.

**Comment by mseri** [comment]
What is its format?

**Comment by gaborigloi** [comment]
```
export XE_EXTRA_ARGS="server=<server address>,port=443,username=<username>,password=<password>"
```

**Comment by mseri** [comment]
ugh.... more stuff to parse...

**Comment by mseri** [comment]
The current master supports reading the configuration from a file, in `.config/xmlrpc/config.prefs.json`. I think it's good enough given that the current client is practically a hack, but it saves me a lot of troubles having to continuously rewrite the same things :D
